---
- name: Create missing directories
  become: yes
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    recurse: "{{ item.recurse }}"
  with_items:
    - { path: "{{ portainer_data_volume }}", recurse: no}

- name: Create portainer files
  become: yes
  template:
    src: "{{ item.template }}.j2"
    dest: "{{ item.path }}/{{ item.template }}"
    mode: "{{ item.mode }}"
    group: docker
  with_items:
    - { template: docker-compose-portainer.yml , path: "{{ node_home }}", mode: '0644' }
    - { template: portainer_start.sh , path: "{{ node_home }}", mode: '0755' }

- name: Run the container
  become: yes
  command: "bash {{ node_home }}/portainer_start.sh"
